version: '3'

services:
  web-server:
    image: nginx:stable-alpine
    container_name: oop-parking-web-server
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - database

  database:
    image: mysql:5.7.22
    container_name: oop-parking-database
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oop-parking-app
    volumes:
      - ./src:/var/www/app
    ports:
      - "9000:9000"